### ISSUE TITLE
Bug: Setting allowMissing for a module using Node.js built-in modules causes error to be thrown

### ISSUE THREAD

**Issue by martinnabhan** [FormidableLabs/trace-deps#42]
First of all thank you Ryan and everyone at Formidable for some amazing packages!

In this particular case when using serverless-jetpack tracing with allowMissing, trace-deps causes a "Could not find source file: http" error.

My serverless config:
```
    trace:
      allowMissing:
        node-fetch:
          - encoding
      ignores:
        - aws-sdk
```

The error:
```
  Error: Could not find source file: http
      at/node_modules/trace-deps/lib/trace.js:170:37
      at traceFile (node_modules/trace-deps/lib/trace.js:166:15)
      at _recurseDeps (node_modules/trace-deps/lib/trace.js:101:22)
      at traceFile (node_modules/trace-deps/lib/trace.js:295:20)
      at _recurseDeps (node_modules/trace-deps/lib/trace.js:101:22)
      at traceFile (node_modules/trace-deps/lib/trace.js:295:20)
      at _recurseDeps (node_modules/trace-deps/lib/trace.js:101:22)
      at traceFile (node_modules/trace-deps/lib/trace.js:295:20)
      at _recurseDeps (node_modules/trace-deps/lib/trace.js:101:22)
      at traceFiles (node_modules/trace-deps/lib/trace.js:349:19)
      at globAndZip (node_modules/serverless-jetpack/util/bundle.js:512:20)
      at Jetpack.globAndZip (node_modules/serverless-jetpack/index.js:744:21)
      at Jetpack.packageService (node_modules/serverless-jetpack/index.js:822:21)
```

The package in question, node-fetch, has code like this:
```
var Stream = _interopDefault(require('stream'));
var http = _interopDefault(require('http'));
var Url = _interopDefault(require('url'));
var https = _interopDefault(require('https'));
var zlib = _interopDefault(require('zlib'));

...

let convert;
try {
	convert = require('encoding').convert;
} catch (e) {}

```

Basically, in traceFile when a package matches allowMissing it seems the package is removed from allPaths:
https://github.com/FormidableLabs/trace-deps/blob/53d62d343576aef09fdaabba34528351b8e4d5e1/lib/trace.js#L252-L258
https://github.com/FormidableLabs/trace-deps/blob/53d62d343576aef09fdaabba34528351b8e4d5e1/lib/trace.js#L283-L284

which causes the index used in the following filtering step to match the wrong package:
https://github.com/FormidableLabs/trace-deps/blob/53d62d343576aef09fdaabba34528351b8e4d5e1/lib/trace.js#L285-L286

I'll be opening a pull request fixing this issue shortly!

**Comment by MartinN13** [comment]
I've opened a pull request and would be super happy if you could take a look!

**Comment by MartinN13** [comment]
I'm sorry, seems like some tests aren't passing. I'll have another look!
